### ISSUE TITLE
EvacBlock.java onBlockAdded called twice

### ISSUE THREAD

**Issue by taddeimania** [taddeimania/safety-line-mod#2]
Why is the block method `onBlockAdded` called twice when I create a block?

**Comment by NerdsvilleCEO** [comment]
I won't be able to look into this until next week, if it can wait until Monday I will take a look :) Let me know if it's been fixed before then

**Comment by taddeimania** [comment]
oh no rush - just streaming atm. wanted to make a note.

**Comment by taddeimania** [comment]
Was able to provide a workaround for this. `onBlockAdded` stills seems to be called twice for every call but I added a check in the method that will not add a block if it sees it in the list.

https://github.com/taddeimania/safety-line-mod/blob/dceb798effefc5c71ae85068c2af0f90ef48fdb2/java/com/test/safetymod/SafetyMod.java#L31

Obviously the next step will be removing a waypoint from that list if the block is removed from the world.
